feat(News):  Add new news system without package + updates dependancies
Zekarant/Mangas-Fan-V8 pull request #3
Opened 2023-05-28 15:52 UTC by Zekarant

2023-05-28 17:55 UTC, teradrive65k commented on assets/css/admin.scss
> +  background-color: #212529!important;
A chaque fois que je vois !important je m'interroge :smile: Peut-on l'eviter ? Je ne suis pas un expert en front css etc, mais ça me fait toujours un peu peur.

2023-05-28 17:55 UTC, teradrive65k commented on assets/js/app.js
> +global.$ = global.jQuery = $;
Impossible de faire cela en vanilla js ? Jquery un peu old non ?

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +    public function adminNews(NewsRepository $newsRepository)
Ne retire pas le response :scream: , essaies au contraire de toujours bien typer. Un controller retourne toujours une Response sur symfony alors rajoute laisse le :)

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +    public function createNews(Request $request, SluggerInterface $slugger, Security $security, EntityManagerInterface $entityManager, WebhookDiscordService $webhookDiscordService)
Ici aussi laisse le Response.

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +        $this->webhookDiscordService = $webhookDiscordService;
Ne set pas ici webhookDiscordService. En fait Symfony te permet de rajouter des services et tes dependances directement en les rajoutant comme arguments dans tes controllers. Tu peux directement utiliser $webhookDiscordService. Si vraiment tu veux vraiment set un service avec this mieux vaut le faire dans un constructeur. Mais tu n'en as pas vraiment besoin ici.

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +        $news->setAuthor($security->getUser());
Tu es dans un controller qui étend AbstractController. Cette classe justement te donne pleins de raccourcis. En l'occurence $this->getUser() je crois. Fait un ctrl click sur $this->getUser() pour voir un peu comment symfony fait cela.

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +        $form->handleRequest($request);
Petit saut de ligne pour bien séparer le contexte je crée un formulaire et je vois si il est valide par la suite.

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
Tout ce qui est en rapport avec deplacer le fichier doit être mis dans un service. Ce n'est pas la responsabilité du controller de faire cela mais c'est plus celle d'un service. L'avantage c'est que par la suite, une fois crée, ton service d'upload de fichier peut être utilisé ailleurs.

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +                        $this->getParameter('uploads_directory'),
:+1:

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +                $image = new Images();
Pourquoi Image au pluriel :thinking: Ce n'est pas en rapport avec ta pr, mais ça serait cool qu'on on le change pa la suite.

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +                $entityManager->persist($image);
On peut s'eviter le persit si il y'a un lien entre une entité A et une entité B en precisant persist dans les relation Doctrine. Ne te prend pas la tete avec ça pour l'instant mais c'est pour info --> https://yusufbiberoglu.medium.com/cascade-persist-remove-in-doctrine-559ac967e451

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +            $this->webhookDiscordService->sendMessageEmbed($news->getTitleNews(), $news->getDescriptionNews(), $news->getSlug(), 123456, true, $newFilename);
Pas la pein du $this. Just $webhookDiscordService suffit.

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
> +        }
Petit saut de ligne.

2023-05-28 17:55 UTC, teradrive65k commented on src/Form/Type/NewsType.php
> +            'attr' => array(
Priveligie toujours la notation moderne pour les array [] que array. Dans les outils de qualité cette notation est directement remplacé justement par les  [] --> https://www.php.net/manual/en/language.types.array.php  regarde l'exemple 1

2023-05-28 17:55 UTC, teradrive65k commented on src/Controller/NewsController.php
>              'news' => $newsRepository->findBy(array(), array('id' => 'DESC'), 15)
Toujours utiliser la notation moderne. Aussi ce findBy gagne à avoir une methode à lui dans le repository. Qqchose comme findLastNews(int $limit = 15) par exemple.

2023-05-28 17:55 UTC, teradrive65k commented on templates/news/admin/create.html.twig
> +    <script src="{{ asset('build/js/selectize.js') }}"></script>
A quoi sert ce selectsize ? juste pour info Car y'a moyen d'utiliser Symfony Ux pour faire des choses très stylés maintenant https://ux.symfony.com/ . Pour l'instant c'est très bien comme ça mais on pourrait evoluer vers ux ça serait cool.

2023-05-28 17:55 UTC, teradrive65k commented on src/Service/WebhookDiscordService.php
> +        private function imageNews($imageTest): ImageEmbedDiscordWebhook {
L'accolade pas sur la meme ligne pour respecter psr12 (je crois de mémoire) https://www.php-fig.org/psr/psr-12/

2023-05-28 17:55 UTC, teradrive65k commented on src/Service/WebhookDiscordService.php
> +            $image->setUrl('https://127.0.0.1:8000/uploads/' . $imageTest);
Ici il ne faut pas mettre en dur l'url mais plutot profiter des paramètres en injection.

2023-05-28 17:55 UTC, teradrive65k commented on src/Service/WebhookDiscordService.php
> +        public function sendMessageEmbed(string $title, string $description, string $url, int $color, bool $showAuthor, string $image): void {
Je trouve que cette méthode à un poil trop de paramètres... A voir si tu peux pas la diviser en deux.

2023-05-28 17:55 UTC, teradrive65k commented on src/Form/Type/NewsType.php
> +        ->addEventListener(FormEvents::PRE_SUBMIT, function(FormEvent $event){
Très bonne idée de metre cela dans un event. Ce n'est pas vraiment necessaire pour le moment mais sache que tu peux aussi mettre l'event dans sa propre classe.

2023-05-28 17:55 UTC, teradrive65k commented on src/Form/Type/NewsType.php
> +        ->addEventListener(FormEvents::PRE_SUBMIT, function(FormEvent $event){
Cette méthode ne renvoie rien donc precise le dansle retour de la fonction:
fuction(...): void

2023-05-28 17:55 UTC, teradrive65k commented on src/Form/Type/NewsType.php
> +            'attr' => array(
[]

2023-05-28 17:55 UTC, teradrive65k commented on src/Form/Type/NewsType.php
> +                'class' => 'form-control bg-dark mb-4 text-light',
Ces class css ne peuvent pas être directement rajouté dans le template ?? J'ai toujours un peu peur de voir ça, meme si même dans un contexte professionel je l'ai pas mal rencontré, mais voilà. Avoir du php qui dit comment les choses doivent s'afficher me fait toujours un peu tilté.

2023-05-28 17:55 UTC, teradrive65k commented on src/Form/Type/NewsType.php
>              'attr' => array(
[]

2023-05-28 19:03 UTC, Zekarant commented on assets/css/admin.scss
> +  background-color: #212529!important;
Le important me sert simplement pour passer par dessus le CSS natif du module. Je pourrai directement le modifier à la source cela dit

2023-05-28 19:03 UTC, Zekarant commented on assets/js/app.js
> +global.$ = global.jQuery = $;
J'ai vu beaucoup de gens le faire en jQuery donc j'ai essayé

2023-05-28 19:04 UTC, Zekarant commented on src/Controller/NewsController.php
> +    public function adminNews(NewsRepository $newsRepository)
Je les avais enlevé car PHPStorm me disait que c'était pas renouvellé en PHP 8 les types de réponses

2023-05-28 19:05 UTC, Zekarant commented on src/Controller/NewsController.php
> +                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
J'ai pas encore bien vu les services donc je ne sais pas trop comment ça marche, mais je note !

2023-05-28 19:06 UTC, Zekarant commented on src/Controller/NewsController.php
> +                $image = new Images();
Parce que l'entité s'appelle Images, on stock en base les images

2023-05-28 19:15 UTC, teradrive65k commented on src/Controller/NewsController.php
> +    public function adminNews(NewsRepository $newsRepository)
Bizarre ... en php 8 ??? Bizarre bizarre, parfois il dit un peu n'importe quoi.

2023-05-28 19:15 UTC, teradrive65k commented on assets/css/admin.scss
> +  background-color: #212529!important;
Oui j'avais compris :) pas de soucis.

2023-05-28 19:15 UTC, teradrive65k commented on assets/js/app.js
> +global.$ = global.jQuery = $;
Okay pas de soucis

2023-08-17 19:21 UTC, Amphi62 requested changes

2023-08-17 19:21 UTC, Amphi62 commented on assets/css/navbar.scss
> +    align-items: center
il manque un point virgule

2023-08-17 19:21 UTC, Amphi62 commented on package.json
> +    "jquery": "^3.7.0"
a mettre de côté mais faudra checker pour ne plus avoir a utiliser du jquery (je suppose que c'est parce qu'un autre module requiert du Jquery mais je pense que y'a des autres solutions), c'est lourd pour rien et je suppose que y'a mieux (en faire un ticket sur trello ?)

2023-08-17 19:21 UTC, Amphi62 commented on public/uploads/2492174.jpg
l'image n'est pas nommé sous le même format que les autres, c'est normal ? (faire le tri sur les autres images si pas normal)

peut-être aussi envisager de gitignore le dossier d'uploads, car si chacun fait des tests et que les nouvelles images s'envoie ça risque d'être assez lourd

à voir aussi si on ne pourrait pas passer par un service de stockage cloud (exemple Amazon S3), un CDN (type Faslty) voir OneDrive ou Dropbox par exemple. C'est des alternatives payantes (à voir en détail les prix), et à en rediscuter plus tard, mais ça serait à mon avis un + pour le stockage des images upload

2023-08-17 19:21 UTC, Amphi62 commented on src/Controller/Admin/DashboardController.php
> +            // ]);
pourquoi c'est commenté ? si ça ne compte plus être utilisé, go le delete

2023-08-17 19:21 UTC, Amphi62 commented on src/Controller/Admin/NewsCrudController.php
> +            ->setFormTypeOption('attr', ['placeholder' => 'Slug automatique']);
? y'a pas moyen de rendre nous même le champ non modifiable ?

2023-08-17 19:21 UTC, Amphi62 commented on src/Controller/Admin/NewsCrudController.php
> +        yield DateTimeField::new('updatedAt', 'Date de mise à jour')->hideOnForm();
le champ s'affiche dans quel condition du coup ? (hideOnForm() si j'ai bien compris la doc c'est que ton champ s'affiche ni quand tu crées une nouvelle entité, ni quand tu l'edit, donc je comprends pas quand ça nous sert)

2023-08-17 19:21 UTC, Amphi62 commented on src/Controller/Admin/UserCrudController.php
> +       //yield TextField::new('password')->setFormType(PasswordType::class)->onlyOnForms();
a supprimer (le EasyAdmin pour les User, c'est juste pour pouvoir les update et les delete on est bien d'accord ?, car l'ajout j'en verrais pas l'utilité)

2023-08-17 19:21 UTC, Amphi62 commented on src/Controller/HomeController.php
>              'last_mangas' => $tomeMangasRepository->findBy(array(), array('createdAt' => 'DESC'), 6),
passer par des `[ ... ]` au lieu de `array(...)`

2023-08-17 19:21 UTC, Amphi62 commented on src/Entity/News.php
> +    private ?string $image = 'default_image.png';
pas de risque que 255 soit limite en terme de place ? (si le slug est bien fait normalement non mais je demande quand même)

2023-08-17 19:21 UTC, Amphi62 commented on src/Entity/News.php
> +    private ?bool $visibility = true;
j'ai un doute, mais ça set up vraiment visibility à true en bdd quand il est pas defined dans un formulaire par exemple ?

2023-08-17 19:21 UTC, Amphi62 commented on src/EventSubscriber/AdminSubscriber.php
> +            $this->webhookDiscordService->sendMessageEmbed($news->getTitleNews(), $news->getDescriptionNews(), $news->getSlug(), 8388980, true, 'https://www.mangasfan.fr/lib/images/logoblanc.png');
il correspond à quoi le chiffre ? une constante serait peut être + parlante
ça commence d'ailleurs à faire beaucoup de paramètre, on pourrait pas directement faire passer $news en paramètre plutôt que 3 de ses attributs dans 3 paramètres distincts ?

2023-08-17 19:21 UTC, Amphi62 commented on templates/news/item_news.html.twig
>              <h2 class="titleNews">{{ new.titleNews }}</h2>
camelCase pas ouf en convention css, `news-card` serait déjà better

2023-08-17 19:24 UTC, Amphi62 requested changes

2023-08-17 19:24 UTC, Amphi62 commented on assets/css/navbar.scss
>  #container, #imageReseaux {
franglais

2023-08-17 20:43 UTC, Zekarant commented on src/Controller/Admin/NewsCrudController.php
> +        yield DateTimeField::new('updatedAt', 'Date de mise à jour')->hideOnForm();
Ca sert pour avoir l'info sur l'accueil
![image](https://github.com/Zekarant/Mangas-Fan-V8/assets/29504908/87d925f4-ba6d-4611-84c2-d8c979f255b7)

2023-08-17 20:44 UTC, Zekarant commented on src/Entity/News.php
> +    private ?bool $visibility = true;
Ca met 1 si true, 0 si false en BDD

2023-08-17 20:45 UTC, Zekarant commented on src/EventSubscriber/AdminSubscriber.php
> +            $this->webhookDiscordService->sendMessageEmbed($news->getTitleNews(), $news->getDescriptionNews(), $news->getSlug(), 8388980, true, 'https://www.mangasfan.fr/lib/images/logoblanc.png');
J'ai pas compris, mais le chiffre, code couleur du bandeau gauche dans le salon news du serveur principal de MF

2023-08-17 21:07 UTC, Amphi62 commented on src/Controller/Admin/NewsCrudController.php
> +        yield DateTimeField::new('updatedAt', 'Date de mise à jour')->hideOnForm();
ok ok

2023-08-17 21:11 UTC, Amphi62 commented on src/EventSubscriber/AdminSubscriber.php
> +            $this->webhookDiscordService->sendMessageEmbed($news->getTitleNews(), $news->getDescriptionNews(), $news->getSlug(), 8388980, true, 'https://www.mangasfan.fr/lib/images/logoblanc.png');
stock ton chiffre dans une constante pour que ce soit plus parlant, genre 
```php
const RED_BORDER = 8388980; 
```
je ne sais plus si ça se défini comme ça en php par contre, à revérifier

2023-08-17 21:23 UTC, Zekarant commented on src/Controller/Admin/DashboardController.php
> +            // ]);
Je ne sais pas si je garde l'option pour une quelconque fonctionnalité

2023-08-17 21:24 UTC, Zekarant commented on src/Entity/News.php
> +    private ?string $image = 'default_image.png';
J'vais enlever la limite

2023-08-17 23:15 UTC, Amphi62 commented on src/Controller/Admin/DashboardController.php
> +            // ]);
ok ok gardons le dans le doute dans ce cas là

2023-08-23 17:02 UTC, closed without merging